apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickup-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickup-app
  template:
    metadata:
      labels:
        app: pickup-app
    spec:
      containers:
      - name: backend
        image: krmp-d2hub-idock.9rum.cc/dev-test/repo_7b9f0e9e3499
        env:
        - name: KAKAO_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: client_id
        - name: KAKAO_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: client_secret
        - name: AWS_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: accesskey
        - name: AWS_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: secretkey
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://pickup-mysql-dev:3306/pickup?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        ports:
        - containerPort: 8080
