namespace: default
resources:
  - backend-deployment.yaml
  - mysql.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - mysql-init/01_init.sql
      - mysql-init/02_create_table.sql
      - mysql-init/03_insert_data.sql