apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickup-mysql-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickup-mysql
  template:
    metadata:
      labels:
        app: pickup-mysql
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:8.0.27
        env:
        - name: MYSQL_DATABASE
          value: "pickup"
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
